spring:
  application:
    name: springconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/skjalal/project-config-properties.git
          search-paths:
            - springconfigclient
    bus:
      enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 8888