spring:
  application:
    name: springconfigserver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoint:
    bus-env:
      enabled: true
    bus-refresh:
      enabled: true
  security:
    enabled: false