spring:
  application:
    name: springconfigserver
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/skjalal/springconfigserver.git
          search-paths:
            - springconfigclient
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
